// Generates supabase/seed.sql from the demo mock data, so live mode starts with the same stalls.
// Run: node scripts/gen-seed.mts
import { writeFileSync } from "node:fs";
import { campaigns, critics, CURRENT_USER_ID, stalls } from "../src/lib/mock-data.ts";

const q = (s: string | null | undefined) => (s == null ? "null" : `'${s.replace(/'/g, "''")}'`);
const json = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;
const textArray = (xs: string[]) => (xs.length ? `array[${xs.map(q).join(", ")}]::text[]` : "'{}'::text[]");
const profileRef = (handle: string) => `(select id from public.profiles where handle = ${q(handle)})`;

// The demo "you" isn't a real person in live mode; their finds are credited to another seeded critic.
const handleFor = (id: string) => (id === CURRENT_USER_ID ? "karthik" : id);

const lines: string[] = [
  "-- Generated by scripts/gen-seed.mts. Run after migrations/0001_hissa.sql.",
  "begin;",
  "",
];

for (const c of critics.filter((c) => c.id !== CURRENT_USER_ID)) {
  lines.push(
    `insert into public.profiles (handle, name, avatar, area, persona, taste_base, reviews_base, found_base, followers, badges) values (` +
      [q(c.handle), q(c.name), q(c.avatar), q(c.area), q(c.persona), c.tasteScore, c.reviews, c.stallsSuggested, c.followers, json(c.badges)].join(", ") +
      ");",
  );
}
lines.push("");

for (const s of stalls) {
  lines.push(
    `insert into public.stalls (id, status, name, vendor_name, vendor_avatar, vendor_quote, area, lat, lng, emoji, hue, dish, tags, veg, avg_price, timings, base_ratings, base_count, verified, suggested_by, since, dishes, ai_summary) values (` +
      [
        q(s.id),
        q(s.verified ? "live" : "pending"),
        q(s.name),
        q(s.vendorName),
        q(s.vendorAvatar),
        q(s.vendorQuote),
        q(s.area),
        s.lat,
        s.lng,
        q(s.emoji),
        s.hue,
        q(s.dish),
        textArray(s.tags),
        s.veg,
        s.avgPrice,
        q(s.timings),
        json(s.ratings),
        s.ratingCount,
        s.verified,
        s.suggestedBy ? profileRef(handleFor(s.suggestedBy)) : "null",
        s.since,
        json(s.dishes),
        q(s.aiSummary),
      ].join(", ") +
      ");",
  );
}
lines.push("");

for (const s of stalls) {
  for (const r of s.reviews.filter((r) => r.userId !== CURRENT_USER_ID)) {
    lines.push(
      `insert into public.ratings (stall_id, profile_id, taste, hygiene, value, vibe, review, is_seed, created_at) values (` +
        [q(s.id), profileRef(r.userId), r.rating, r.rating, r.rating, r.rating, q(r.text), "true", q(r.date)].join(", ") +
        ");",
    );
  }
}
lines.push("");

// Pending stalls start with two vouches, so one real player's vouch brings them live.
for (const s of stalls.filter((s) => !s.verified)) {
  for (const handle of ["karthik", "meera"]) {
    lines.push(`insert into public.vouches (stall_id, profile_id) values (${q(s.id)}, ${profileRef(handle)});`);
  }
}
lines.push("");

for (const c of campaigns) {
  lines.push(
    `insert into public.campaigns (id, stall_id, title, short_goal, story, goal, raised, backers, ends_on, cost_breakdown, revenue_share, milestones, insight, updates) values (` +
      [
        q(c.id),
        q(c.stallId),
        q(c.title),
        q(c.shortGoal),
        q(c.story),
        c.goal,
        c.raised,
        c.backers,
        `current_date + ${c.endsInDays}`,
        json(c.costBreakdown),
        json(c.revenueShare),
        json(c.milestones),
        json(c.insight),
        json(c.updates),
      ].join(", ") +
      ");",
  );
  lines.push(`update public.stalls set campaign_id = ${q(c.id)} where id = ${q(c.stallId)};`);
}

lines.push("", "commit;", "");
writeFileSync(new URL("../supabase/seed.sql", import.meta.url), lines.join("\n"));
console.log(`Wrote supabase/seed.sql (${critics.length - 1} critics, ${stalls.length} stalls, ${campaigns.length} campaigns)`);
